from enum import StrEnum


class DataClass(StrEnum):
    SYNTHETIC_SILVER = "SYNTHETIC_SILVER"
    PROXY_GOLD_SIMULATION = "PROXY_GOLD_SIMULATION"
    PHARMACIST_GOLD = "PHARMACIST_GOLD"
    EXTERNAL_BLIND = "EXTERNAL_BLIND"
    SYNTHETIC_OUTCOME_PROXY = "SYNTHETIC_OUTCOME_PROXY"
    SYNTHETIC_SAFETY_PROXY = "SYNTHETIC_SAFETY_PROXY"
    SIMULATED_INTEGRATION_PROXY = "SIMULATED_INTEGRATION_PROXY"
    REAL_WORLD_OUTCOME = "REAL_WORLD_OUTCOME"
    INTERIM_RUNTIME_EVENT = "INTERIM_RUNTIME_EVENT"


class EventPayloadState(StrEnum):
    ACTIVE = "ACTIVE"
    CORRECTED = "CORRECTED"
    DELETED = "DELETED"


class ReplacementStatus(StrEnum):
    PENDING_PHARMACIST_GOLD = "PENDING_PHARMACIST_GOLD"
    PENDING_REAL_WORLD_OUTCOME = "PENDING_REAL_WORLD_OUTCOME"
    PENDING_12_MONTH_REAL_OPERATION = "PENDING_12_MONTH_REAL_OPERATION"
    PENDING_PRODUCTION_DEVICE_SESSIONS = "PENDING_PRODUCTION_DEVICE_SESSIONS"
    PENDING_EXTERNAL_TEST = "PENDING_EXTERNAL_TEST"
