"""Deterministic candidate generation, constraints, and scoring."""

from wellnessbox_rnd.optimizer.constraints import (
    OptimizationCandidateFactsV1,
    OptimizationConstraintEvaluationV1,
    OptimizationConstraintsV1,
    evaluate_optimization_candidate_v1,
)
from wellnessbox_rnd.optimizer.product_combinations import (
    CatalogProductIdentityV1,
    IngredientDoseTotalV1,
    ProductCombinationCartCandidateV1,
    ProductCombinationEvidenceV1,
    ProductCombinationFilterEvaluationV1,
    ProductCombinationFilterPolicyV1,
    ProductCombinationInventoryContextV1,
    ProductCombinationNonSelectionV1,
    ProductCombinationOptimizationInputV1,
    ProductCombinationRankingEvidenceV1,
    ProductCombinationReplayIdentityV1,
    ProductCombinationStockCartEvidenceV1,
    ProductCombinationStockSubstitutionV1,
    ProductCombinationV1,
    ProductIngredientAmountV1,
    ProductOfferV1,
    RankedProductCombinationV1,
    SelectedProductV1,
    evaluate_product_combination_filters_v1,
    evaluate_product_combination_ranking_v1,
)

__all__ = [
    "CatalogProductIdentityV1",
    "OptimizationCandidateFactsV1",
    "OptimizationConstraintEvaluationV1",
    "OptimizationConstraintsV1",
    "evaluate_optimization_candidate_v1",
    "IngredientDoseTotalV1",
    "ProductCombinationEvidenceV1",
    "ProductCombinationFilterEvaluationV1",
    "ProductCombinationFilterPolicyV1",
    "ProductCombinationNonSelectionV1",
    "ProductCombinationOptimizationInputV1",
    "ProductCombinationInventoryContextV1",
    "ProductCombinationStockCartEvidenceV1",
    "ProductCombinationStockSubstitutionV1",
    "ProductCombinationCartCandidateV1",
    "ProductCombinationRankingEvidenceV1",
    "ProductCombinationReplayIdentityV1",
    "ProductCombinationV1",
    "ProductIngredientAmountV1",
    "ProductOfferV1",
    "SelectedProductV1",
    "evaluate_product_combination_filters_v1",
    "evaluate_product_combination_ranking_v1",
    "RankedProductCombinationV1",
]
