const pathUtil = require("node:path") as typeof import("node:path");
const { buildHotspotCodeRows } = require("../lib/hotspot-code-files.cts") as {
  buildHotspotCodeRows: (
    rootDir: string
  ) => Array<{
    abs: string;
    file: string;
    lines: number;
  }>;
};
const {
  isScriptFile,
  isApiRouteFile,
  isFrontendSurfaceFile,
} = require("../lib/hotspot-paths.cts") as {
  isScriptFile: (file: string) => boolean;
  isApiRouteFile: (file: string) => boolean;
  isFrontendSurfaceFile: (file: string) => boolean;
};
const { writeIfChanged } = require("../lib/write-if-changed.cts") as {
  writeIfChanged: (options: {
    outputPath: string;
    content: string;
    rootDir?: string;
    encoding?: BufferEncoding;
  }) => {
    changed: boolean;
    outputPath: string;
    relativePath: string;
  };
};

type Row = {
  file: string;
  lines: number;
};

const REPO_ROOT = process.cwd();
const OUTPUT_PATH = pathUtil.join(REPO_ROOT, "REFACTOR_HOTSPOTS.md");

function topRows(rows: Row[], size: number) {
  return [...rows]
    .sort((a, b) => b.lines - a.lines || a.file.localeCompare(b.file))
    .slice(0, size);
}

function topRowsByFilter(
  rows: Row[],
  size: number,
  predicate: (row: Row) => boolean
) {
  return topRows(rows.filter(predicate), size);
}

function section(title: string, rows: Row[]) {
  const lines: string[] = [];
  lines.push(`## ${title}`);
  lines.push("");
  lines.push("| Lines | File |");
  lines.push("|---:|---|");
  for (const row of rows) {
    lines.push(`| ${row.lines} | \`${row.file}\` |`);
  }
  lines.push("");
  return lines.join("\n");
}

function main() {
  const files = buildHotspotCodeRows(REPO_ROOT);

  const runtimeRows: Row[] = [];
  const scriptRows: Row[] = [];

  for (const item of files) {
    if (isScriptFile(item.file)) {
      scriptRows.push({ file: item.file, lines: item.lines });
      continue;
    }
    runtimeRows.push({ file: item.file, lines: item.lines });
  }

  const topRuntime = topRows(runtimeRows, 25);
  const topApiRoutes = topRowsByFilter(runtimeRows, 20, (row) =>
    isApiRouteFile(row.file)
  );
  const topFrontendSurfaces = topRowsByFilter(runtimeRows, 20, (row) =>
    isFrontendSurfaceFile(row.file)
  );
  const topScripts = topRows(scriptRows, 15);

  const doc: string[] = [];
  doc.push("# Refactor Hotspots");
  doc.push("");
  doc.push("Auto-generated by `scripts/agent/generate-refactor-report.cts`.");
  doc.push("Run `npm run agent:refactor-report` to refresh this report.");
  doc.push("");
  doc.push(section("Runtime Top 25", topRuntime));
  doc.push(section("API Route Top 20", topApiRoutes));
  doc.push(section("Frontend Surface Top 20", topFrontendSurfaces));
  doc.push(section("Scripts Top 15", topScripts));
  doc.push("## Notes");
  doc.push("");
  doc.push("- Refresh companion checks with `npm run audit:hotspots` after major changes.");
  doc.push("- Prefer splitting orchestration-heavy files before pure data/config files.");
  doc.push("- For UI files, extract presentational sections first, then hook logic.");
  doc.push("- Re-run after each major refactor to validate actual reduction.");
  doc.push("");

  const nextContent = doc.join("\n");
  const writeResult = writeIfChanged({
    outputPath: OUTPUT_PATH,
    content: nextContent,
    rootDir: REPO_ROOT,
  });
  if (writeResult.changed) {
    console.log(`Wrote hotspot report: ${writeResult.relativePath}`);
  } else {
    console.log(`Hotspot report unchanged: ${writeResult.relativePath}`);
  }
}

main();
